---
- hosts: all
  
  tasks:
    - name: Ping 
      ansible.builtin.ping:

- hosts: user_api
  become: yes
  vars :
       java_app_location: /app/users-api

  tasks:
    - name: Install java
      apt: 
        update_cache: true 
        state: present
        name: 
          - openjdk-8-jdk
          - maven

    - name: Correct java version selected
      community.general.alternatives:
        name: java
        path: /usr/lib/jvm/java-8-openjdk-amd64/bin/java

    - name: Fetch Java version
      shell:
        cmd: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
      register: java_version

    - assert:
        that: 
          - "java_version.stdout is version('1.8.0_362','eq')"     

    - name: Clone the repository
      git:
        repo: https://github.com/PJCB1998/DevOpsRampUp-users-api.git
        dest: "{{ java_app_location }}"

    - name: Ensure java app folder exists.
      file: "path={{ java_app_location }} state=directory"

    - name: Move users-api.service
      command: 
        cmd: cp {{ java_app_location }}/users-api.service /etc/systemd/system  
    
    - name: Install dependencies
      command: 
        cmd: "{{ java_app_location }}/mvnw clean install"
        chdir: "{{ java_app_location }}"
        creates: "{{ java_app_location }}/target"
        
    - name: Run the application
      command:
        cmd: systemctl start users-api.service


- hosts: auth_api
  become: yes
  vars :
       go_app_location: /app/auth-api

  tasks:
    - name: Add Golang Backports PPA Repositroy 
      apt_repository: 
        repo: ppa:longsleep/golang-backports 
        update_cache: true

    - name: Install go
      apt: 
        update_cache: true 
        state: present
        name: 
          - golang-go

    - name: Clone the repository
      git:
        repo: https://github.com/PJCB1998/DevOpsRampUp-auth-api.git
        dest: "{{ go_app_location }}"

    - name: Ensure go app folder exists.
      file: "path={{ go_app_location }} state=directory"

    - name: Move auth-api.service
      command: 
        cmd: cp {{ go_app_location }}/auth-api.service /etc/systemd/system  
    
    - name: Build go app
      command: 
        cmd: "{{ go_app_location }}/build-auth-api.sh"
        chdir: "{{ go_app_location }}"
        creates: "{{ go_app_location }}/auth-api"
        
    - name: Run the application
      command:
        cmd: systemctl start auth-api.service


- hosts: todo_api
  become: yes
  vars :
       node_app_location: /app/todo-api

  tasks:
    - name: Install nodejs and npm
      apt: 
        update_cache: true 
        state: present
        name: 
          - npm
          - nodejs

    - name: Clone the repository
      git:
        repo: https://github.com/PJCB1998/DevOpsRampUp-todos-api.git
        dest: "{{ node_app_location }}"

    - name: Ensure node app folder exists.
      file: "path={{ node_app_location }} state=directory"

    - name: Move todo-api.service
      command: 
        cmd: cp {{ node_app_location }}/todo-api.service /etc/systemd/system  
    
    - name: Build node app
      command: 
        cmd: "/usr/bin/npm install"
        chdir: "{{ node_app_location }}"
        
    - name: Run the application
      command:
        cmd: systemctl start todo-api.service